# -*- coding: utf-8 -*-
"""Baseline_idm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W1IahaDIF0d4BBzsF3TpsSxc8kflHrw5
"""

import numpy as np
import matplotlib.pyplot as plt

def idm_acceleration(h, delta_v, v, v0=30.0, T0=1.5, s0=2.0, a_max=0.73, b=1.63, delta=4):
    """
    Computes follower acceleration using Intelligent Driver Model (IDM).

    Parameters:
    - h: Spacing to leader (meters)
    - delta_v: Velocity difference (v_follower - v_leader in m/s)
    - v: Follower velocity (m/s)
    """
    # 1. Desired minimum spacing
    s_star = s0 + v * T0 + (v * delta_v) / (2.0 * np.sqrt(a_max * b))

    # 2. Acceleration calculation
    free_road_term = (v / v0) ** delta
    interaction_term = (s_star / np.maximum(h, 0.1)) ** 2

    acc = a_max * (1.0 - free_road_term - interaction_term)
    return np.clip(acc, -3.0, a_max)

# --- Quick Simulation: Leader brakes suddenly ---
time_steps = 150
dt = 0.1

time = np.linspace(0, time_steps * dt, time_steps)
v_leader = np.full(time_steps, 20.0) # Lead vehicle moves at 20 m/s
v_leader[30:70] = 12.0               # Lead vehicle slows down to 12 m/s

# Follower initial conditions
h = 35.0   # initial gap in meters
v = 20.0   # initial speed in m/s

h_history, v_history, a_history = [], [], []

for t in range(time_steps):
    delta_v = v - v_leader[t]
    acc = idm_acceleration(h, delta_v, v)

    # Update follower state (Euler integration)
    v = max(0.0, v + acc * dt)
    h = max(0.5, h - delta_v * dt)

    h_history.append(h)
    v_history.append(v)
    a_history.append(acc)

# --- Plot the Results ---
plt.figure(figsize=(10, 4))
plt.subplot(1, 2, 1)
plt.plot(time, v_leader, 'b--', label='Lead Vehicle Speed')
plt.plot(time, v_history, 'r', label='Ego Vehicle Speed (IDM)')
plt.xlabel('Time (s)')
plt.ylabel('Speed (m/s)')
plt.legend()
plt.title('Vehicle Velocity')

plt.subplot(1, 2, 2)
plt.plot(time, a_history, 'g', label='Ego Acceleration')
plt.xlabel('Time (s)')
plt.ylabel('Acceleration (m/s²)')
plt.legend()
plt.title('Control Action')

plt.tight_layout()
plt.show()