# -*- coding: utf-8 -*-
"""icacc_env_validation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IjA2pTQgyaec-szvtS02PrBDnzWxaq6i
"""

import numpy as np
import matplotlib.pyplot as plt

class IntentCACCEnv:
    """
    Simulation Environment for 2-Vehicle Intent-Sharing CACC (I-CACC).
    Formulation: Kanipakam, Sakr, Avedisov, Moradipari (IEEE 2024).
    """
    def __init__(self):
        # Time and Horizon Parameters (Section II & Table II)
        self.dt = 0.1             # Sampling interval ΔT = 0.1s
        self.tau_max = 2.0        # Intent horizon τ_max = 2.0s
        self.horizon_steps = int(self.tau_max / self.dt) # 20 steps
        self.tau_ss = 2.0         # String stability history window τ_ss = 2.0s
        self.ss_steps = int(self.tau_ss / self.dt)       # 20 steps
        self.gamma_ss = 0.99      # String stability coefficient

        # Platooning & Safety Constants (Table II)
        self.d_min = 2.0          # Minimum standstill buffer (meters)
        self.th_star = 1.5        # Desired time headway t_h* (seconds)
        self.tc_star = 3.0        # Time-to-Collision safety threshold t_c* (seconds)
        self.a_max = 3.0          # Max acceleration limit (m/s^2)
        self.a_min = -3.0         # Max deceleration limit (m/s^2)

        # Reward Normalization & Objective Weights (Section III & Table II)
        self.k_j = 2.7e-4         # Jerk scaling
        self.k_s = 1.0            # String stability penalty weight
        self.k_e = 0.5            # Gap error exponential scaling
        self.weights = [1.0, 4.0, 2.0, 1.0]  # [w_c (safety), w_j (comfort), w_s (string), w_e (gap)]

    def reset(self, init_ego_v=20.0, init_lead_v=20.0, init_dist=32.0):
        """Resets the platoon state (ego and leader kinematics)."""
        self.v_e = float(init_ego_v)
        self.v_l = float(init_lead_v)
        self.d_e = float(init_dist)
        self.a_e_prev = 0.0
        self.lead_acc_history = [0.0] * self.ss_steps

        # Return initial 12D observation vector
        state_12d, _, _ = self._get_state(0.0, 0.0, 0.0, [0.0] * self.horizon_steps)
        return state_12d

    def _get_state(self, a_e, a_l, delta_v, lead_future_acc):
        """Constructs the 12-dimensional state vector s(t) (Eq. 4)."""
        # Extract intent bounds from the received broadcast
        a_l_min = float(np.min(lead_future_acc))
        a_l_max = float(np.max(lead_future_acc))

        # Instantaneous metrics
        e_e = self.d_e - (self.d_min + self.th_star * self.v_e)
        t_h_mean = self.d_e / max(self.v_e, 0.1)

        # Time-to-Collision (TTC) bounds
        if delta_v > 0:
            t_c = self.d_e / max(delta_v, 1e-4)
            t_c_min = min(t_c, self.tc_star)
        else:
            t_c = 100.0
            t_c_min = self.tc_star

        # Intent-projected bounds over tau_max
        e_e_min = e_e - 0.5 * abs(a_l_min - a_e) * (self.tau_max ** 2)
        e_e_max = e_e + 0.5 * abs(a_l_max - a_e) * (self.tau_max ** 2)

        state_12d = np.array([
            self.v_e, self.d_e, delta_v, self.a_e_prev,
            a_l, a_l_min, a_l_max, t_c_min, t_h_mean,
            e_e, e_e_min, e_e_max
        ], dtype=np.float32)
        return state_12d, t_c, e_e

    def step(self, a_e_cmd, lead_future_acc):
        """
        Executes one discrete simulation step (ΔT = 0.1s).
        lead_future_acc: array of future lead accelerations over tau_max (20 steps).
        """
        a_e = float(np.clip(a_e_cmd, self.a_min, self.a_max))
        a_l = float(lead_future_acc[0])

        # 1. State transitions: discrete Euler integration (Eq. 2 & 3)
        delta_v_prev = self.v_e - self.v_l
        self.v_e = max(0.0, self.v_e + a_e * self.dt)
        self.v_l = max(0.0, self.v_l + a_l * self.dt)
        delta_v_curr = self.v_e - self.v_l
        self.d_e = max(0.1, self.d_e - 0.5 * (delta_v_prev + delta_v_curr) * self.dt)

        # Update rolling leader acceleration history
        self.lead_acc_history.pop(0)
        self.lead_acc_history.append(a_l)

        # 2. Get 12D State Vector s(t)
        state_12d, t_c, e_e = self._get_state(a_e, a_l, delta_v_curr, lead_future_acc)

        # 3. Multi-Objective Reward Calculation (Section III-A)
        # Safety Reward r_c
        r_c = np.log(t_c / self.tc_star) if t_c <= self.tc_star else 0.0

        # Comfort Reward r_j (Jerk penalty)
        jerk = (a_e - self.a_e_prev) / self.dt
        r_j = -self.k_j * (jerk ** 2)

        # String Stability Reward r_s (Eq. 10)
        a_e_lim = self.gamma_ss * np.max(np.abs(self.lead_acc_history))
        r_s = -self.k_s * (abs(a_e) - a_e_lim) if abs(a_e) > a_e_lim else 0.0

        # Gap Keeping Reward r_e (Eq. 11)
        r_e = np.exp(-self.k_e * (e_e ** 2))

        # Weighted Total Reward (Eq. 12)
        r_total = (self.weights[0] * r_c +
                   self.weights[1] * r_j +
                   self.weights[2] * r_s +
                   self.weights[3] * r_e)

        self.a_e_prev = a_e
        info = {"r_c": r_c, "r_j": r_j, "r_s": r_s, "r_e": r_e, "e_e": e_e, "jerk": jerk}
        return state_12d, r_total, info

# Initialize environment
env = IntentCACCEnv()
init_state = env.reset(init_ego_v=20.0, init_lead_v=20.0, init_dist=32.0)

time_steps = 150
# Construct a leader braking profile (decelerates between t=3s and t=7s)
lead_profile = np.zeros(time_steps + env.horizon_steps)
lead_profile[30:70] = -1.8

time_axis = np.linspace(0, time_steps * env.dt, time_steps)
ego_speeds, lead_speeds, gap_errors, total_rewards = [], [], [], []

for t in range(time_steps):
    future_acc = lead_profile[t : t + env.horizon_steps]

    # Proportional-derivative follower control to test dynamics
    desired_gap = env.d_min + env.th_star * env.v_e
    error = env.d_e - desired_gap
    cmd_acc = 0.5 * error - 0.7 * (env.v_e - env.v_l)

    state, r, info = env.step(cmd_acc, future_acc)
    ego_speeds.append(state[0])
    lead_speeds.append(env.v_l)
    gap_errors.append(info["e_e"])
    total_rewards.append(r)

# Generate Validation Plot
fig, axes = plt.subplots(1, 3, figsize=(15, 4))

axes[0].plot(time_axis, lead_speeds, 'b--', label='Leader Speed')
axes[0].plot(time_axis, ego_speeds, 'r-', label='Follower Speed')
axes[0].set_title('Velocity Profiles')
axes[0].set_xlabel('Time (s)')
axes[0].set_ylabel('Speed (m/s)')
axes[0].legend()
axes[0].grid(True, linestyle='--', alpha=0.6)

axes[1].plot(time_axis, gap_errors, 'g-')
axes[1].axhline(0, color='black', linestyle=':', alpha=0.7)
axes[1].set_title('Gap-Keeping Error $e_e(t)$')
axes[1].set_xlabel('Time (s)')
axes[1].set_ylabel('Error (m)')
axes[1].grid(True, linestyle='--', alpha=0.6)

axes[2].plot(time_axis, total_rewards, 'm-')
axes[2].set_title('Multi-Objective Reward $r(t)$')
axes[2].set_xlabel('Time (s)')
axes[2].set_ylabel('Step Reward')
axes[2].grid(True, linestyle='--', alpha=0.6)

plt.tight_layout()
plt.savefig("icacc_env_validation.png")
plt.show()