# -*- coding: utf-8 -*-
"""pidl_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yZVYBQPE-4TtL3D5zXzJrtlgw4lFbp7q
"""

import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
import matplotlib.pyplot as plt

# -------------------------------------------------------------
# 1. Physics-Uninformed Neural Network (PUNN) Architecture
#    3 hidden layers (60 neurons each) with tanh activation (Mo et al., 2021)
# -------------------------------------------------------------
class PUNN(nn.Module):
    def __init__(self, input_dim=3, hidden_dim=60, output_dim=1):
        super(PUNN, self).__init__()
        self.net = nn.Sequential(
            nn.Linear(input_dim, hidden_dim),
            nn.Tanh(),
            nn.Linear(hidden_dim, hidden_dim),
            nn.Tanh(),
            nn.Linear(hidden_dim, hidden_dim),
            nn.Tanh(),
            nn.Linear(hidden_dim, output_dim)
        )
        self._init_weights()

    def _init_weights(self):
        for m in self.net:
            if isinstance(m, nn.Linear):
                nn.init.xavier_uniform_(m.weight)
                nn.init.zeros_(m.bias)

    def forward(self, x):
        return self.net(x)

# -------------------------------------------------------------
# 2. Physics Model (IDM) in PyTorch Tensors
# -------------------------------------------------------------
def idm_physics_torch(states, v0=30.0, T0=1.5, s0=2.0, a_max=0.73, b=1.63, delta=4.0):
    """
    Computes IDM acceleration directly on PyTorch tensors.
    states: Tensor of shape (N, 3) where columns are [h, delta_v, v]
    """
    h = states[:, 0:1]
    delta_v = states[:, 1:2]
    v = states[:, 2:3]

    s_star = s0 + v * T0 + (v * delta_v) / (2.0 * np.sqrt(a_max * b))
    free_road = (v / v0) ** delta
    interaction = (s_star / torch.clamp(h, min=0.1)) ** 2

    acc = a_max * (1.0 - free_road - interaction)
    return torch.clamp(acc, min=-3.0, max=a_max)

# -------------------------------------------------------------
# 3. Hybrid PIDL Loss Function
# -------------------------------------------------------------
def pidl_loss(model, obs_states, obs_actions, colloc_states, alpha=0.7):
    # Data discrepancy (MSE_O)
    pred_obs_actions = model(obs_states)
    mse_o = torch.mean((pred_obs_actions - obs_actions) ** 2)

    # Physics discrepancy (MSE_C)
    pred_colloc_actions = model(colloc_states)
    phy_colloc_actions = idm_physics_torch(colloc_states)
    mse_c = torch.mean((pred_colloc_actions - phy_colloc_actions) ** 2)

    total_loss = alpha * mse_o + (1.0 - alpha) * mse_c
    return total_loss, mse_o, mse_c

# -------------------------------------------------------------
# 4. Synthetic Training Pipeline Demonstration
# -------------------------------------------------------------
# Generate synthetic observed states: [h, delta_v, v]
np.random.seed(42)
n_obs = 60
obs_h = np.random.uniform(10, 50, (n_obs, 1))
obs_dv = np.random.uniform(-5, 5, (n_obs, 1))
obs_v = np.random.uniform(10, 25, (n_obs, 1))
obs_s = np.hstack([obs_h, obs_dv, obs_v])

# Generate target actions using IDM + small noise
obs_s_tensor = torch.tensor(obs_s, dtype=torch.float32)
obs_a_tensor = idm_physics_torch(obs_s_tensor) + 0.05 * torch.randn((n_obs, 1))

# Generate collocation points (unobserved grid)
n_colloc = 100
colloc_h = np.random.uniform(5, 60, (n_colloc, 1))
colloc_dv = np.random.uniform(-10, 10, (n_colloc, 1))
colloc_v = np.random.uniform(0, 30, (n_colloc, 1))
colloc_s_tensor = torch.tensor(np.hstack([colloc_h, colloc_dv, colloc_v]), dtype=torch.float32)

# Instantiate model and optimizer
model = PUNN()
optimizer = optim.Adam(model.parameters(), lr=0.001)

# Training loop
epochs = 200
loss_history = []

for epoch in range(epochs):
    optimizer.zero_grad()
    loss, mse_o, mse_c = pidl_loss(model, obs_s_tensor, obs_a_tensor, colloc_s_tensor, alpha=0.7)
    loss.backward()
    optimizer.step()
    loss_history.append(loss.item())

# Plot training curve
plt.figure(figsize=(7, 3.5))
plt.plot(loss_history, label='PIDL Total Loss', color='darkblue')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.title('PIDL-IDM Model Training Convergence')
plt.grid(True, linestyle='--', alpha=0.6)
plt.legend()
plt.tight_layout()
plt.show()